const part1Data = [
    { id: 1, q: "Nội dung nào dưới đây thể hiện việc xác định các nguồn thu nhập khi xây dựng kế hoạch chi tiêu trong gia đình?", opts: ["A. Ghi chép các khoản chi tiêu hàng ngày.", "B. Thống nhất tỷ lệ phân chia các khoản.", "C. Chủ động tiềm kiếm nguồn thu nhập.", "D. Xác định khoản chi tiêu thiết yếu."], a: "C" },
    { id: 2, q: "Nội dung nào dưới đây thể hiện việc thực hiện các khoản thu chi trong gia đình theo kế hoạch?", opts: ["A. Thống nhất tỷ lệ phân chia các khoản.", "B. Ghi chép các khoản chi tiêu hàng ngày.", "C. Chủ động tìm kiếm nguồn thu nhập.", "D. Xác định khoản chi tiêu thiết yếu."], a: "B" },
    { id: 3, q: "Khi thống nhất tỷ lệ phân chia các khoản chi tiêu, các gia đình không cần phân chi tỷ lệ cho nội dung nào dưới đây?", opts: ["A. Chi thiết yếu.", "B. Chi nộp thuế nhà đất.", "C. Chi không thiết yếu.", "D. Chi tiết kiệm."], a: "B" },
    { id: 4, q: "Khi lập kế hoạch quản lý thu chi trong gia đình, việc thống nhất các khoản chi thiết yếu và không thiết yếu cần đảm bảo nguyên tắc nào dưới đây?", opts: ["A. Ưu tiên cho khoản không thiết yếu.", "B. Dành toàn bộ cho khoản không thiết yếu.", "C. Dành toàn bộ cho khoản thiết yếu", "D. Ưu tiên cho khoản chi tiêu thiết yếu."], a: "D" },
    { id: 5, q: "Nội dung nào dưới đây không phải là căn cứ để xây dựng kế hoạch quản lý thu, chi trong gia đình?", opts: ["A. Các khoản chi tiêu trong gia đình.", "B. Các mối quan hệ trong gia đình.", "C. Mục tiêu tài chính trong gia đình.", "D. Các nguồn thu nhập trong gia đình."], a: "B" },
    { id: 6, q: "Những khoản chi tiêu nào dưới đây trong gia đình là khoản chi tiêu không thiết yếu?", opts: ["A. Chi phí điện nước.", "B. Chi phí học tập.", "C. Chi phí xem phim.", "D. Chi phí ăn, mặc."], a: "C" },
    { id: 7, q: "Kế hoạch quản lý thu chi trong gia đình không bao gồm nội dung nào dưới đây?", opts: ["A. Xác định mục tiêu tài chính trong gia đình.", "B. Xác định các nguồn thu nhập trong gia đình.", "C. Xác định các khoản chi tiêu thiết yếu.", "D. Xác định kế hoạch thu lợi nhuận kinh doanh."], a: "D" },
    { id: 8, q: "Để biết được tình hình tài chính hiện tại từ đó có cơ sở để xây dựng kế hoạch tài chính, mỗi gia đình cần xác định được", opts: ["A. các vấn đề sẽ phát sinh sau hôn nhân.", "B. các nguồn thu nhập trong gia đình.", "C. các biện pháp thúc đẩy bình đẳng giới.", "D. các mối quan hệ trong và ngoài gia đình."], a: "B" },
    { id: 9, q: "Gia đình bạn B đặt mục tiêu: sau 3 tháng mua xe đạp điện, sau 3 năm có tiền học đại học, sau 10 năm mua chung cư. Mục tiêu tài chính nào dưới đây không được gia đình bạn B xác định?", opts: ["A. Trung hạn.", "B. Dài hạn.", "C. Không thời hạn", "D. Ngắn hạn."], a: "C" },
    { id: 10, q: "Một trong những mục đích của việc thực hiện quản lý thu, chi trong gia đình là nhằm", opts: ["A. cân bằng các mối quan hệ.", "B. mối quan hệ cha mẹ và con.", "C. cân bằng các khoản chi.", "D. cân bằng tài chính gia đình."], a: "D" },
    { id: 11, q: "Nội dung nào dưới đây không phải là tiêu chí khi xác định mục tiêu tài chính của gia đình?", opts: ["A. Mục tiêu tài chính vô hạn.", "B. Mục tiêu tài chính ngắn hạn.", "C. Mục tiêu tài chính trung hạn.", "D. Mục tiêu tài chính dài hạn."], a: "A" },
    { id: 12, q: "Quản lý thu chi trong gia đình là việc sử dụng các nội dung nào dưới đây để đáp ứng nhu cầu vật chất và tinh thần của các thành viên trong gia đình?", opts: ["A. Các khoản chi.", "B. Các khoản tài trợ.", "C. Các khoản thu, chi.", "D. Các khoản thu."], a: "C" },
    { id: 13, q: "Nội dung nào dưới đây thể hiện việc xác định các khoản chi tiêu trong gia đình khi lập kế hoạch quản lý thu chi?", opts: ["A. Chủ động tìm kiếm nguồn thu nhập.", "B. Xác định khoản chi tiêu thiết yếu.", "C. Ghi chép các khoản chi tiêu hàng ngày.", "D. Thống nhất tỷ lệ phân chia các khoản."], a: "B" },
    { id: 14, q: "Để xây dựng kế hoạch quản lý thu, chi hợp lý, mỗi gia đình cần thảo luận dân chủ để cùng nhau", opts: ["A. xác định vai trò của mỗi cá nhân.", "B. xác định dòng vốn cần đầu tư.", "C. xác định công việc của mỗi thành viên.", "D. xác định mục tiêu tài chính phù hợp."], a: "D" },
    { id: 15, q: "Việc làm nào dưới đây thể hiện thói quen chi tiêu hợp lý trong gia đình?", opts: ["A. Thiết lập mục tiêu tài chính.", "B. Chi tiêu quá mức thu nhập.", "C. Không xây dựng quỹ dự phòng.", "D. Chi tiêu không có kế hoạch."], a: "A" },
    { id: 16, q: "Nguồn thu nhập trong gia đình không bao gồm khoản nào dưới đây?", opts: ["A. Thu nhập từ tiền cho thuê nhà.", "B. Thu nhập từ tiền thưởng.", "C. Thu nhập từ kinh tế đối ngoại.", "D. Thu nhập từ tài sản thừa kế."], a: "C" },
    { id: 17, q: "Thông qua việc thực hiện quản lý thu, chi trong gia đình một cách phù hợp sẽ góp phần giúp", opts: ["A. nâng cao chất lượng cuộc sống.", "B. nâng cao vai trò của người vợ.", "C. tạo ra sự mâu thuẫn, chia rẽ.", "D. nâng cao vai trò của người chồng."], a: "A" },
    { id: 18, q: "Phát biểu nào dưới đây là sai về sự cần thiết phải quản lý thu chi trong gia đình?", opts: ["A. Quản lý thu chi trong gia đình giúp nâng cao chất lượng cuộc sống gia đình.", "B. Quản lý thu chi trong gia đình giúp kiểm soát các nguồn thu trong gia đình.", "C. Quản lý thu chi trong gia đình góp phần điều chỉnh thói quen chi tiêu không hợp lý.", "D. Quản lý thu chi trong gia đình sẽ gia tăng các tình huống rủi ro trong gia đình."], a: "D" },
    { id: 19, q: "Để thực hiện được mục tiêu cho con đi du học như dự định, với nguồn thu nhập hiện tại chị T nên cắt giảm các khoản chi tiêu nào dưới đây?", opts: ["A. Chi tiêu thiết yếu.", "B. Các khoản tiết kiệm.", "C. Các khoản dự phòng.", "D. Chi tiêu không thiết yếu."], a: "D" },
    { id: 20, q: "Kế hoạch quản lý thu chi trong gia đình của chị T trong thông tin trên không bao gồm khoản chi nào dưới đây?", opts: ["A. Chi phí không thiết yếu.", "B. Chi đầu tư kinh doanh.", "C. Chi tiết kiệm, dự phòng.", "D. Chi phí thiết yếu."], a: "B" },
    { id: 21, q: "Theo quy định, khi tiến hành kinh doanh, mọi doanh nghiệp đều phải thực hiện nghĩa vụ", opts: ["A. sử dụng nguyên liệu hữu cơ.", "B. đầu tư kinh phí quảng cáo.", "C. bảo vệ quyền lợi người tiêu dùng.", "D. tổ chức hội nghị trực tuyến định kì."], a: "C" },
    { id: 22, q: "Trong quá trình sản xuất kinh doanh, nếu phát sinh các khoản liên quan đến thuế, người sản xuất kinh doanh có nghĩa vụ nào dưới đây?", opts: ["A. Kê khai trung thực, chính xác.", "B. Hoàn thuế để gia tăng lợi nhuận.", "C. Che giấu làm sai lệch hồ sơ.", "D. Khiếu nại quyền lợi về thuế."], a: "A" },
    { id: 23, q: "Cơ quan chức năng X đã vi phạm quyền kinh doanh của công dân ở nội dung nào dưới đây khi duyệt hồ sơ của M (thiếu) mà không duyệt H (đủ)?", opts: ["A. Chủ động mở rộng quy mô.", "B. Tích cực tìm kiếm thị trường.", "C. Khuyến khích tự do liên kết.", "D. Tự chủ đăng kí kinh doanh."], a: "D" },
    { id: 24, q: "Quyền của người nộp thuế không thể hiện ở việc mọi công dân đều được", opts: ["A. cung cấp thông tin về nộp thuế.", "B. hoàn thuế nếu có đủ điều kiện.", "C. từ chối nộp thuế nếu có nhu cầu.", "D. giữ bí mật thông tin nộp thuế."], a: "C" },
    { id: 25, q: "Theo quy định, quyền của công dân về kinh doanh không thể hiện ở việc mọi doanh nghiệp đều được", opts: ["A. Nộp thuế đầy đủ theo quy định.", "B. Lựa chọn địa điểm sản xuất.", "C. Mở rộng quy mô sản xuất.", "D. Tuyển dụng lao động phù hợp."], a: "A" },
    { id: 26, q: "Phát biểu nào dưới đây là sai về nghĩa vụ kinh doanh của công dân?", opts: ["A. Công dân được khiếu nại nếu phát hiện hành vi vi phạm về kinh doanh.", "B. Bảo vệ quyền lợi người tiêu dùng là trách nhiệm của chủ thể kinh doanh.", "C. Khi kinh doanh, công dân có nghĩa vụ nộp thuế đầy đủ theo quy định.", "D. Công dân có trách nhiệm tôn trọng quyền tự do kinh doanh của người khác."], a: "A" },
    { id: 27, q: "Anh X mở rộng đại lý tại nhiều địa phương. Anh X đã thực hiện quyền nào?", opts: ["A. Kê khai và nộp thuế đầy đủ.", "B. Tuyển dụng lao động trực tuyến.", "C. Chủ động mở rộng thị trường.", "D. Chủ động ký kết lao động tự do."], a: "C" },
    { id: 28, q: "Nội dung nào dưới đây không thể hiện quyền của công dân khi kinh doanh?", opts: ["A. Thực hiện việc chia đều của cải xã hội.", "B. Đăng ký thương hiệu cho hàng hóa.", "C. Chủ động mở rộng thị trường xuất khẩu.", "D. Thực hiện cổ phần hóa doanh nghiệp."], a: "A" },
    { id: 29, q: "Nội dung nào dưới đây là nghĩa vụ của công dân về nộp thuế?", opts: ["A. Tôn trọng quyền nộp thuế của người khác.", "B. Tố cáo hành vi gian lận thuế nhập khẩu.", "C. Được hoàn thuế giá trị gia tăng.", "D. Cung cấp thông tin thực hiện nghĩa vụ thuế."], a: "D" },
    { id: 30, q: "Công ty Q bán bánh kẹo dù giấy phép là quần áo trẻ em. Công ty Q vi phạm quyền nào?", opts: ["A. Mở rộng thị trường, quy mô kinh doanh.", "B. Chủ động lựa chọn ngành, nghề kinh doanh.", "C. Kinh doanh đúng ngành, nghề đã đăng kí.", "D. Tự chủ kinh doanh tìm kiếm thị trường."], a: "C" },
    { id: 31, q: "Để bảo vệ quyền của người nộp thuế, pháp luật nghiêm cấm hành vi nào?", opts: ["A. Lợi dụng chiếm đoạt tiền thuế.", "B. Khiếu nại liên quan đến thuế.", "C. Tố cáo hành vi vi phạm về thuế.", "D. Cung cấp thông tin về thuế."], a: "A" },
    { id: 32, q: "Quyền của công dân về kinh doanh không thể hiện ở việc được", opts: ["A. phê duyệt ngân sách quốc gia.", "B. tự do liên doanh, liên kết.", "C. mở rộng quy mô sản xuất.", "D. chủ động tìm kiếm thị trường."], a: "A" },
    { id: 33, q: "Anh A cho vợ là B bán thuốc nhưng thực tế bán thực phẩm chức năng không rõ nguồn gốc. Anh A vi phạm gì?", opts: ["A. Tự do hợp đồng lao động.", "B. Kinh doanh đúng giấy phép.", "C. Tự chủ đăng ký kinh doanh.", "D. Mở rộng quy mô kinh doanh."], a: "B" },
    { id: 34, q: "Anh A đăng kí bán thêm thức ăn nhanh bên cạnh tạp hóa. Anh A thực hiện quyền nào?", opts: ["A. Chủ động mở rộng quy mô.", "B. Thay đổi loại hình doanh nghiệp.", "C. Tự do tuyển dụng chuyên gia.", "D. Tích cực nhập khẩu nguyên liệu."], a: "A" },
    { id: 35, q: "Ông C không kê khai mặt hàng mới để trốn thuế. Ông C vi phạm nghĩa vụ gì?", opts: ["A. Sử dụng không đúng mã số thuế.", "B. Chiếm đoạt tiền hoàn thuế.", "C. Kê khai không trung thực.", "D. Nộp thuế không đúng thời hạn."], a: "C" },
    { id: 36, q: "Nội dung nào phù hợp với nghĩa vụ khi kinh doanh?", opts: ["A. Bán những mặt hàng không đăng ký kinh doanh.", "B. Kê khai không chính xác các mặt hành chịu thuế.", "C. Mở cửa hàng bán đồ dùng sinh hoạt gia đình", "D. Đăng ký kinh doanh với cơ quan chức năng."], a: "D" },
    { id: 37, q: "Biện pháp nào không được áp dụng với ông C về hành vi trốn thuế?", opts: ["A. Xử phạt vi phạm hành chính.", "B. Truy thu số thuế còn thiếu.", "C. Miễn thuế và rút kinh nghiệm.", "D. Bổ sung tờ khai nộp thuế."], a: "C" },
    { id: 38, q: "Ai phải chịu trách nhiệm pháp lý về hành vi vi phạm quyền/nghĩa vụ kinh doanh? (K mua của H hàng bẩn, N bao che K phạt H)", opts: ["A. Anh G và ông N.", "B. Anh K, chị H và anh G.", "C. Anh K, chị H và ông N.", "D. Anh K và anh G."], a: "C" },
    { id: 39, q: "Chủ thể nào vi phạm nghĩa vụ công dân khi kinh doanh?", opts: ["A. Anh G và ông N.", "B. Anh K và ông N.", "C. Anh K và chị H.", "D. Chị H và ông N."], a: "C" },
    { id: 40, q: "Chị H thực hiện quyền gì về kinh doanh?", opts: ["A. Khiếu nại để bảo vệ quyền lợi.", "B. Tự chủ đăng ký kinh doanh.", "C. Tố cáo hành vi vi phạm kinh doanh.", "D. Mở rộng quy mô sản xuất."], a: "C" },
    { id: 41, q: "Phát biểu nào đúng về quyền sở hữu tài sản?", opts: ["A. Người không phải chủ sở hữu cũng có quyền bán tài sản mà mình quản lí.", "B. Chủ sở hữu có quyền bán tài sản của mình cho người khác.", "C. Người được chủ sở hữu giao cho quản lí tài sản cũng có quyền định đoạt tài sản ấy.", "D. Người được chủ sở hữu cho mượn tài sản có quyền sử dụng tuỳ theo ý của mình."], a: "B" },
    { id: 42, q: "Khi thực hiện quyền chiếm hữu, công dân phải thực hiện nghĩa vụ nào?", opts: ["A. Khai thác và hưởng hoa lợi.", "B. Chi phối và quản lý tài sản.", "C. Tôn trọng quy định pháp luật.", "D. Ủy quyền người khác quản lý"], a: "C" },
    { id: 43, q: "Người mượn tài sản phải giữ gìn, trả đúng hạn, hỏng phải đền là khái niệm nào?", opts: ["A. Quyền định đoạt tài sản của người khác.", "B. Nghĩa vụ tôn trọng tài sản của người khác.", "C. Quyền sử dụng tài sản khi được cho mượn", "D. Nghĩa vụ từ chối bảo vệ tài sản người khác."], a: "B" },
    { id: 44, q: "Quyền sở hữu tài sản bao gồm các quyền nào?", opts: ["A. quyết định, sử dụng, mua bán tài sản.", "B. chiếm hữu, phân chia tài sản.", "C. sử dụng, cho mượn tài sản.", "D. chiếm hữu, sử dụng, định đoạt tài sản."], a: "D" },
    { id: 45, q: "Quyền tự quản lý, chi phối trực tiếp tài sản là quyền", opts: ["A. chiếm hữu tài sản.", "B. sử dụng tài sản.", "C. cho mượn tài sản.", "D. định đoạt tài sản."], a: "A" },
    { id: 46, q: "Chủ sở hữu có quyền sử dụng nào?", opts: ["A. Khai thác tài sản tuyệt đối theo ý chí của mình.", "B. Khai thác tài sản vì mục tiêu lợi nhuận tối cao.", "C. Khai thác tài sản theo mọi địa điểm, thời gian.", "D. Khai thác công dụng, hướng hoa lợi, lợi tức từ tài sản."], a: "D" },
    { id: 47, q: "Chủ sở hữu tài sản không được thực hiện hành vi nào?", opts: ["A. trái đạo đức xã hội.", "B. quyền hưởng lợi.", "C. tiêu hủy tài sản.", "D. quyền chi phối."], a: "A" },
    { id: 48, q: "Xâm phạm quyền sở hữu tài sản có thể bị xử lý thế nào?", opts: ["A. Xử lí hành chính trong phạm vi nội bộ cơ quan.", "B. Xử phạt theo yêu cầu của người bị vi phạm.", "C. Xử phạt vi phạm hành chính hoặc xử lí hình sự.", "D. Xử phạt về hành vi không tôn trọng pháp luật"], a: "C" },
    { id: 49, q: "Người không phải là chủ sở hữu có quyền chiếm hữu khi", opts: ["A. có đầy đủ nhân thân.", "B. được pháp luật cho phép.", "C. được người thân đồng ý.", "D. được tập thể suy tôn."], a: "B" },
    { id: 50, q: "Khi sử dụng tài sản, chủ sở hữu không được", opts: ["A. Xâm phạm lợi ích người khác.", "B. Hưởng lợi tức từ tài sản.", "C. Hưởng hoa lợi từ tài sản.", "D. Khai thác công dụng tài sản."], a: "A" },
    { id: 51, q: "G và X (thuê phòng rồi làm tiền giả) đã vi phạm quyền nào?", opts: ["A. Quyền định đoạt.", "B. Quyền chiếm hữu.", "C. Quyền từ chối.", "D. Quyền sử dụng."], a: "D" },
    { id: 52, q: "N, X và G cùng chưa thực hiện tốt nghĩa vụ nào? (liên quan đến thuê nhà/xe)", opts: ["A. Tôn trọng tài sản của người khác.", "B. Kê khai tạm trú tạm vắng.", "C. Đóng tiền nhà đúng quy định.", "D. Đóng thuế thu nhập cá nhân."], a: "A" },
    { id: 53, q: "Ai là chủ sở hữu tài sản trong thông tin? (Y chủ trọ, N mượn xe X, G lái xe N làm hỏng)", opts: ["A. Bà Y, anh X  và anh G.", "B. Anh N và anh X.", "C. Bà Y, anh N và anh X.", "D. Bà Y và anh N."], a: "C" },
    { id: 54, q: "Ai chưa thực hiện đúng nghĩa vụ tôn trọng tài sản? (Ông B lấn đất, M thuê trái phép, D, N trộm xe)", opts: ["A. Anh D và ông M.", "B. Ông B và chị P.", "C. Anh D và anh N.", "D. Ông M và anh N."], a: "A" },
    { id: 55, q: "Ai là chủ sở hữu tài sản hợp pháp? (B đất, P xe, M thuê, D/N trộm)", opts: ["A. Anh D và ông M.", "B. Ông M và chị P.", "C. Ông B và ông M.", "D. Ông B và chị P."], a: "D" },
    { id: 56, q: "Chủ thể nào có thể được thực hiện quyền sử dụng đối với tài sản?", opts: ["A. Anh D, chị P và anh N.", "B. Ông B, ông M và anh N.", "C. Ông M, anh D và chị P.", "D. Ông B, ông M và chị P."], a: "D" },
    { id: 57, q: "Chủ thể nào có quyền định đoạt đối với tài sản của chủ sở hữu?", opts: ["A. Anh D và chị P.", "B. Ông B và chị P.", "C. Anh D và anh N.", "D. Ông B và ông M."], a: "B" },
    { id: 58, q: "Chủ thể nào thực hiện quyền của chủ sở hữu? (A xe bị đập, E xe bị C làm hỏng gương, D điện thoại)", opts: ["A. Anh A, anh E và anh C.", "B. Anh B, anh A và anh E", "C. Anh C, anh D và anh E.", "D. Anh D, anh A và anh E."], a: "D" },
    { id: 59, q: "Chủ thể nào chưa thực hiện tốt nghĩa vụ tôn trọng tài sản?", opts: ["A. Anh C, anh B và anh E.", "B. Anh A, anh C và anh E", "C. Anh E và anh B", "D. Anh B, anh C và anh D", "E. Anh C, anh D và anh E."], a: "E" },
    { id: 60, q: "Chủ thể nào không phải chịu trách nhiệm pháp lý về vi phạm nghĩa vụ tôn trọng tài sản?", opts: ["A. Anh C và anh E.", "B. Anh A và anh B.", "C. Anh E và anh B", "D. Anh A và anh D."], a: "B" },
    { id: 61, q: "Anh H tự quyết định nơi cư trú không bàn với vợ, vi phạm quyền bình đẳng nào?", opts: ["A. tài sản chung.", "B. tài sản và sở hữu.", "C. nhân thân.", "D. sở hữu."], a: "C" },
    { id: 62, q: "Vợ chồng bình đẳng với nhau trong việc", opts: ["A. Công khai danh tính người tố cáo.", "B. đề xuất mức lương khởi điểm.", "C. chăm lo giáo dục con phát triển.", "D. làm trái thỏa ước lao động tập thể."], a: "C" },
    { id: 63, q: "Tự do trong hôn nhân thể hiện qua việc cá nhân được tự do", opts: ["A. Lấy bất cứ ai mà mình thích.", "B. Kết hôn theo luật định.", "C. Kết hôn ở độ tuổi mình thích.", "D. Lấy vợ, chồng theo ý muốn gia đình."], a: "B" },
    { id: 64, q: "Cha mẹ có quyền và nghĩa vụ ngang nhau trong việc cùng", opts: ["A. áp đặt quan điểm cá nhân.", "B. bác bỏ hôn nhân tiến bộ.", "C. chăm sóc, giáo dục con.", "D. che dấu hành vi bạo lực."], a: "C" },
    { id: 65, q: "Vợ, chồng có quyền và nghĩa vụ ngang nhau trong việc", opts: ["A. tổ chức đối thoại truyền thống.", "B. kế hoạch điều tra nhân lực.", "C. kế hoạch hóa gia đình.", "D. quản lý bằng hệ thống phần mềm."], a: "C" },
    { id: 66, q: "V bán vàng bố mẹ cho. Mẹ chồng K tức giận. Mẹ đẻ P xúc phạm K. Ai vi phạm?", opts: ["A. Bà K và chồng chị V.", "B. Bà K, chồng chị V và bà P.", "C. Bà K và bà P.", "D. Vợ chồng chị V, bà K và bà P."], a: "C" },
    { id: 67, q: "Khi mục đích hôn nhân không đạt, ai không có thẩm quyền đề nghị ly hôn?", opts: ["A. Người chồng.", "B. Người vợ.", "C. Cả hai vợ chồng.", "D. Người bảo lãnh."], a: "D" },
    { id: 68, q: "Vợ và chồng có trách nhiệm", opts: ["A. sản xuất trái phép chất ma túy", "B. che giấu người nhập cảnh trái phép.", "C. làm giả nhãn hiệu hàng hóa.", "D. tôn trọng nhân phẩm của nhau."], a: "D" },
    { id: 69, q: "Vợ chồng cùng chiếm hữu, sử dụng, định đoạt tài sản chung thể hiện bình đẳng trong", opts: ["A. tìm kiếm việc làm.", "B. quan hệ nhân thân.", "C. quan hệ về tài sản.", "D. việc nuôi dạy con cái."], a: "C" },
    { id: 70, q: "T đánh vợ X. M (chị X) bôi nhọ T. Q (mẹ T) đuổi X, lăng mạ thông gia. Ai vi phạm hôn nhân gia đình?", opts: ["A. Anh T và bà Q.", "B. Anh T, bà Q và chị M.", "C. Chị X, anh T và chị M.", "D. Anh T và chị M."], a: "B" },
    { id: 71, q: "H bị chồng K đánh. Mẹ H thuê P đánh K. Bố K tới lăng nhục mẹ con H. Ai vi phạm hôn nhân gia đình?", opts: ["A. Anh K, bà M và ông T.", "B. Anh K, bà M và anh P.", "C. Chị H, bà M và ông T.", "D. Anh K, chị H và bà M."], a: "A" },
    { id: 72, q: "Cha mẹ có trách nhiệm với con cái là", opts: ["A. tôn trọng ý kiến của con", "B. hỗ trợ nhập cảnh trái phép.", "C. ép làm công việc nặng nhọc.", "D. từ chối việc chăm sóc."], a: "A" },
    { id: 73, q: "F có vợ K, sống như vợ chồng với C, có con riêng. K bàn với S đuổi F để chiếm nhà. Ai vi phạm?", opts: ["A. Anh F và chị C.", "B. Anh F và chị K.", "C. Chị C và chị S.", "D. Anh F, chị C và chị S."], a: "A" },
    { id: 74, q: "Nam từ đủ bao nhiêu tuổi được kết hôn?", opts: ["A. 22 tuổi.", "B. 20 tuổi.", "C. 18 tuổi.", "D. 19 tuổi."], a: "B" },
    { id: 75, q: "Cha mẹ cùng", opts: ["A. áp đặt quan điểm cá nhân", "B. che dấu hành vi bạo lực. .", "C. tôn trọng ý kiến của con.", "D. bác bỏ quyền tự do tôn giáo."], a: "C" },
    { id: 76, q: "Ai vi phạm? (P, G ép D ly hôn/đẻ thuê. T đẻ thuê. K giúp T trộm).", opts: ["A. Ông P, bà G, anh D và chị L.", "B. Ông P, bà G, chị T và chị H.", "C. Ông P, bà G, anh D và chị H.", "D. Ông P, bà G, anh D và anh K."], a: "D" },
    { id: 77, q: "Chủ thể nào vi phạm quyền vợ chồng? (D ép vợ L, T xen vào, K ngoại tình?)", opts: ["A. Chị T và anh K.", "B. Anh D và anh K.", "C. Anh D, chị L và anh K.", "D. Anh D, chị H và anh K."], a: "B" },
    { id: 78, q: "Ai vi phạm hôn nhân? (K đẻ thuê với H. M xúc phạm/thuê người đánh. L xúc phạm M)", opts: ["A. Anh K và chị L.", "B. Anh K, chị M và chị H.", "C. Anh K và chị M.", "D. Anh K, chị M và chị L."], a: "B" },
    { id: 79, q: "Ai vừa vi phạm hôn nhân vừa vi phạm gia đình? (K, M, T)", opts: ["A. Anh K, bà T và chị H.", "B. Anh K, chị M và bà T.", "C. Anh K và chị M.", "D. Chị M và chị L."], a: "B" },
    { id: 80, q: "Chị M tự ý bán đất chung là vi phạm quyền", opts: ["A. Quyền nhân thân.", "B. Quyền kết hôn.", "C. Quyền tài sản.", "D. Quyền ly hôn."], a: "C" },
];
const part2Data = [
    {
        id: 81,
        title: "Câu 81: Quản lý thu chi (Gia đình D và H)",
        text: "Sau khi cưới nhau, anh D và chị H dự định sau 3 năm sẽ mua nhà và ra ở riêng. Vợ chồng anh chị đồng thuận thực hiện kế hoạch quản lí thu, chi bằng số theo dõi hằng tháng sau khi bàn bạc thống nhất. Theo đó, vợ chồng chị sẽ dành 50% tổng thu nhập cho chi tiêu thiết yếu, sinh hoạt hằng ngày; 20% dành cho các khoản dự phòng, tiết kiệm, mua nhà,... và 30% còn lại dành cho các hoạt động giải trí, giao tiếp xã hội,...Sau năm đầu thực hiện, do có tố phát sinh đó là có con nhỏ nên anh chị buộc phải giảm số tiền cho các hoạt động giải trí để tăng cho các sinh hoạt thiết yếu, đặc biệt số tiền giảm này chị đã tham gia một gói bảo hiểm an sinh cho con mình đề phòng lúc ốm đau, mặc dù biết là nhiều mối quan hệ xã hội bị cắt giảm nhưng anh chị vẫn cảm thấy vui và tự tin về mục tiêu tài chính của mình sẽ đạt được.",
        items: [
            { id: 'a', text: "a. Thực hiện kế hoạch thu chi bằng sổ theo dõi hàng tháng là thể hiện việc xác định mục tiêu tài chính trong gia đình.", explanation: "Sai, đây là thể hiện việc thực hiện kế hoạch chi tiêu tài chính trong gia đình.", ans: false },
            { id: 'b', text: "b. Việc tham gia bảo hiểm an sinh cho con mình là biện pháp nhằm tăng nguồn thu nhập cho gia đình.", explanation: "Sai, đây là khoản chi tiêu phục vụ cho sức khỏe và đề phòng rủi ro.", ans: false },
            { id: 'c', text: "c. Kể từ khi có con nhỏ, anh D và chị H đã chủ động cắt giảm các khoản chi không thiết yếu là phù hợp.", explanation: "Đúng, vì những khoản này chưa thực sự cần thiết để tập trung cho các khoản thiết yếu.", ans: true },
            { id: 'd', text: "d. Anh D và chị H xác định mục tiêu tài chính dài hạn là sau 3 năm kết hôn sẽ mua được nhà là chưa phù hợp.", explanation: "Sai, việc này đã được anh chị bàn bạc và thống nhất, với thời gian 3 năm là phù hợp", ans: false }
        ]
    },
    {
        id: 82,
        title: "Câu 82: Quản lý thu chi (Anh T)",
        text: "Khi biết có một căn nhà cũ bán với giá rẻ, anh T liền lên kế hoạch dự trù tài chính, mua lại căn nhà đó để sửa chữa và cho thuê với giá hợp lí. Cách thức này vừa giúp gia đình anh có thêm nguồn thu nhập vừa giữ được tài sản hiện có của anh. Bên cạnh đó, anh T dành một khoản lớn thu nhập cho mục tiêu tiết kiệm. Anh chi tiêu ở mức tối thiểu cho sinh hoạt hằng ngày với các nhu cầu thiết yếu. Anh quan niệm rằng chỉ có tiết kiệm mới có thể thực hiện được mục tiêu mua nhà, mua xe,... Vì vậy, anh hạn chế giao tiếp, không mở rộng quan hệ xã hội để tránh các khoản chi không cần thiết, không mang lại cho anh lợi ích gì.",
        items: [
            { id: 'a', text: "a) Việc phân chia các khoản chi tiêu thiết yếu và không thiết yếu của anh T là hoàn toàn phù hợp.", explanation: "Sai, anh T đang dành quá nhiều cho tiết kiệm, trong khi các khoản chi thiết yếu còn khá ít.", ans: false },
            { id: 'b', text: "b) Hoạt động mua nhà rồi cho thuê lại là khoản thu nhập thụ động trong gia đình.", explanation: "Đúng, khoản này không cần sử dụng sức lao động để đem lại thu nhập.", ans: true },
            { id: 'c', text: "c) Mua nhà và mua xe đây là các mục tiêu tài chính trong gia đình của anh T.", explanation: "Đúng, đây là các mục tiêu anh T đang cần hướng tới.", ans: true },
            { id: 'd', text: "d) Việc hạn chế giao tiếp và không mở rộng quan hệ xã hội nhằm giảm các khoản chi tiêu thiết yếu của anh T là phù hợp.", explanation: "Sai, đây là các khoản chi tiêu không thiết yếu.", ans: false }
        ]
    },
    {
        id: 83,
        title: "Câu 83: Kinh doanh hàng giả (Ông M)",
        text: "Từ năm 2018, ông M thành lập Công ty Trách nhiệm hữu hạn Thương mại và Sản xuất G với ngành nghề kinh doanh dầu nhớt, phụ tùng xe gắn máy. Trong thời gian kinh doanh, ông M nhận thấy khách hàng ưa chuộng các phụ tùng xe gắn máy hiệu H và dầu nhớt hiệu K nên nảy sinh ý định làm giả sản phẩm của các thương hiệu này bán cho khách hàng để thu lợi. Ông M chỉ đạo nhân viên thiết kế các mẫu tem xác nhận hàng chính hãng và thuê người in nhiều mẫu tem để sử dụng, sau đó ông cùng vợ đến một số chợ trong khu vực tìm mua các phụ tùng xe gắn máy, dầu nhớt chất lượng kém đem về đóng gói, dán tem làm giả sản phẩm của các thương hiệu nổi tiếng, bán ra thị trường cho khách với giá thấp hơn hàng chính hãng từ 10% – 15%. Bằng thủ đoạn đó, trong thời gian gần 2 năm, vợ chồng ông M đã sản xuất số lượng hàng giả có giá trị tương đương hàng thật hơn 750 triệu đồng, thu lợi khoảng 300 triệu đồng.",
        items: [
            { id: 'a', text: "a) Hành vi làm giả hàng hóa các thương hiệu nổi tiếng để thu lợi nhuận là vi phạm quyền mở rộng kinh doanh của công dân.", explanation: "Sai đây là hành vi vi phạm quyền tự chủ đăng ký kinh doanh, ở đây ông M lợi dụng việc thành lập công ty để bán một số hàng hóa không có trong danh mục đăng ký.", ans: false },
            { id: 'b', text: "b) Ông M cùng vợ phải chịu trách nhiệm hình sự về hành vi vi phạm pháp luật của mình.", explanation: "Đúng, với giá trị làm hàng giả lên tới 300 triệu đồng, hành vi của ông M và vợ có thể sẽ bị xử lý hình sự.", ans: true },
            { id: 'c', text: "c) Ông M vừa vi phạm nghĩa vụ kinh doanh vừa vi phạm nghĩa vụ nộp thuế cho nhà nước.", explanation: "Đúng hành vi làm hàng giả của ông M đã vi phạm nội dung quyền kinh doanh, đồng thời gián tiếp làm ảnh hưởng đến việc thu thuế của nhà nước.", ans: true },
            { id: 'd', text: "d) Việc thành lập doanh nghiệp của ông M thể hiện quyền của công dân về kinh doanh.", explanation: "Đúng, ông M đã thực hiện quyền của công dân về tự chủ đăng ký kinh doanh.", ans: true }
        ]
    },
    {
        id: 84,
        title: "Câu 84: Nghĩa vụ thuế (Anh D)",
        text: "Anh D hoạt động trong lĩnh vực xuất bản phần mềm cho máy tính. Ngay khi nhận được khoản thu nhập đầu tiên từ công việc, anh D đã chủ động tìm hiểu thông tin về việc nộp thuế để thực hiện nghĩa vụ của mình. Anh D trực tiếp đến cơ quan thuế đề nghị hỗ trợ và được cán bộ cơ quan thuế cung cấp đầy đủ các thông tin liên quan đến quyền và nghĩa vụ nộp thuế. Sau khi nắm được thông tin, anh D đăng kí mã số thuế cá nhân, kê khai đầy đủ thông tin về thu nhập của bản thân và nộp đủ số tiền thuế theo quy định của pháp luật. Thời gian sau đó, mỗi khi đến kì nộp thuế, anh D luôn chủ động khai thuế và nộp thuế đầy đủ, đúng hạn.",
        items: [
            { id: 'a', text: "a) Anh D vừa thực hiện tốt nghĩa vụ kinh doanh vừa thực hiện tốt nghĩa vụ nộp thuế.", explanation: "Đúng, anh đã tuân thủ các quy định về kinh doanh cũng như thực hiện tốt các quy định của pháp luật về nộp thuế.", ans: true },
            { id: 'b', text: "b) Việc anh D được cung cấp đầy đủ các thông tin liên quan đến việc nộp thuế của bản thân thể hiện cơ quan thuế đã thực hiện tốt nghĩa vụ của mình.", explanation: "Đúng, cơ quan thuế có trách nhiệm cung cấp chính xác đầy đủ các thông tin liên quan đến việc nộp thuế của công dân.", ans: true },
            { id: 'c', text: "c) Anh D đã thực hiện tốt trách nhiệm kinh tế của doanh nghiệp khi tiến hành kinh doanh.", explanation: "Sai, việc thực hiện đầy đủ nghĩa vụ thuế là thể hiện trách nhiệm pháp lý của doanh nghiệp.", ans: false },
            { id: 'd', text: "d) Việc đăng ký mã số thuế cá nhân của anh D là thực hiện quyền của công dân về nộp thuế.", explanation: "Sai, đây là thể hiện nghĩa vụ của công dân về nộp thuế.", ans: false }
        ]
    },
    {
        id: 85,
        title: "Câu 85: Tài sản và Tín dụng đen (Anh X, Q, Y)",
        text: "Do kinh doanh tín dụng đen thua lỗ, anh X phải vay của anh Q số tiền 200 triệu đồng. Quá hạn trả nợ, bị anh Q đe dọa nên anh X bàn với em rể mình là anh Y lừa bán chị A ra nước ngoài. Theo đúng thỏa thuận với anh X, anh Y lập kế hoạch cùng chị A đi du lịch. Đến một thị trấn gần biên giới, do điện thoại của mình hết pin, anh Y mượn điện thoại chị A để sử dụng. Trong lúc nghe anh Y trao đổi với anh X, chị A phát hiện âm mưu của hai anh nên tìm cách bỏ trốn nhưng bị anh Y khống chế và đập vỡ điện thoại của chị. Nhờ có anh B là một người đi đường giúp đỡ bằng cách cố ý tạo ra sự hỗn loạn nên chị A chạy thoát và tố cáo sự việc với cơ quan chức năng.",
        items: [
            { id: 'a', text: "a) Công dân được kinh doanh hoạt động tín dụng đen nhưng phải đóng thuế đầy đủ.", explanation: "Sai, tín dụng đen là loại hình tín dụng bị nhà nước đặc biệt nghiêm cấm.", ans: false },
            { id: 'b', text: "b) Anh X và anh Y chưa thực hiện đúng nghĩa vụ tôn trọng tài sản của công dân.", explanation: "Đúng, cụ thể anh X vay tiền nhưng không trả đúng hạn, còn anh Y đập vỡ điện thoại của chị A.", ans: true },
            { id: 'c', text: "c) Anh Q và chị B là chủ sở hữu hợp pháp đối với tài sản của mình là phù hợp.", explanation: "Đúng vì đây là những tài sản thuộc quyền sở hữu hợp pháp của chủ sở hữu.", ans: true },
            { id: 'd', text: "d) Anh Q và chị B có quyền khiếu nại tới có quan chức năng để bảo vệ quyền sở hữu hợp pháp của chủ sở hữu tài sản.", explanation: "Đúng nếu như các cá nhân không thể tự thỏa thuận mức bồi thường thì chủ sở hữu có quyền khởi kiện.", ans: true }
        ]
    },
    {
        id: 86,
        title: "Câu 86: Lừa đảo xuất khẩu lao động (E, S, P)",
        text: "Nhận thấy nhiều thanh niên ở nông thôn đang có nhu cầu tìm việc làm, anh E đã thuê anh S đăng bài tuyển người đi làm việc ở nước ngoài nhằm mục đích lừa đảo. Đọc được thông tin trên bài đăng của anh S, anh P đã mang giấy chứng nhận quyền sử dụng đất của mình đi cầm cố để có tiền chuyển cho anh S. Vì đã vay tiền của mình mà chưa trả được, lo sợ anh P tiếp tục vay tiền của người khác, anh V là anh trai của anh P đã tung tin anh P chơi cá độ bóng đá bị thua. Sau khi nhận từ anh P số tiền 200 triệu đồng, S và E đưa anh P tới tập trung ở một nhà trọ với mục đích bán anh P qua biên giới. Hơn 10 ngày sau, nghi ngờ anh P biết hành vi lừa đảo của mình, E và S liên tục đánh, gây thương tích cho anh P. Khi phát hiện anh P nhắn tin báo cho anh V, E đã giật điện thoại của anh P và kiểm tra tin nhắn, sau đó đưa cho S. Thấy trong điện thoại của anh P có một số hình ảnh của E và mình, S lập tức xóa hết dữ liệu và đập vỡ điện thoại của anh P.",
        items: [
            { id: 'a', text: "a) Anh E tự thuê anh S đăng bài để tuyển lao động đi nước người là hoạt động kinh doanh phù hợp với xu thế kinh doanh online hiện nay.", explanation: "Sai, hoạt động tự đăng ý tuyển lao động đi làm việc ở nước ngoài mà chưa được phép là vi phạm pháp luật.", ans: false },
            { id: 'b', text: "b) Anh P mang giấy chứng nhận quyền sử dụng đất để cầm cố lấy tiền là thực hiện quyền định đoạt tài sản của chủ sở hữu.", explanation: "Đúng, đây là quyền quyết định về tài sản của chủ sở hữu.", ans: true },
            { id: 'c', text: "c) Anh P chưa thực hiện tốt nghĩa vụ tôn trọng tài sản của người khác.", explanation: "Đúng vì anh P vay tiền người khác mà không trả đúng hẹn.", ans: true },
            { id: 'd', text: "d) Anh S phải chịu trách nhiệm dân sự về hành vi vi phạm nghĩa vụ tôn trọng tài sản của công dân.", explanation: "Đúng vì anh S đã đập vỡ điện thoại của anh P tức là không tôn trọng tài sản của người khác.", ans: true }
        ]
    },
    {
        id: 87,
        title: "Câu 87: Vi phạm kinh doanh (S, Q, N, P)",
        text: "Ông S là lãnh đạo, anh Q là nhân viên thuộc một cơ quan nhà nước có thẩm quyền. Trong khi thực hiện nhiệm vụ, ông S, anh Q phát hiện ông N tự ý mở cửa hàng kinh doanh đồ gia dụng và cho anh P thuê một phần diện tích mở cửa hàng bán xe máy điện tại tầng 01 của chung cư do ông N là chủ sở hữu. Vì ông N không bảo đảm yêu cầu về phòng cháy, chữa cháy theo quy định của pháp luật nên ông S cùng anh Q đã lập biên bản và ra quyết định xử phạt vi phạm hành chính đối với ông N. Trong quá trình kiểm tra, phát hiện một số xe máy điện ở cửa hàng của anh P không rõ nguồn gốc nên ông S và anh Q đã tịch thu. Thấy ông N bị xử phạt, thông qua sự môi giới của ông K, ông M là người chuyên bán thiết bị chữa cháy giả đã tìm gặp và đề nghị ông N mua hàng của mình. Sau khi tìm hiểu, biết hàng hóa ông M bán là giả nên ông N từ chối mua. Để đảm bảo an toàn, ông N đề nghị anh P cùng mình lắp đặt thiết bị chữa cháy nhưng bị anh P từ chối. Bực tức, ông N chấm dứt hợp đồng và chiếm đoạt số tiền thuê nhà 06 tháng mà anh P đã thanh toán trước cho ông.",
        items: [
            { id: 'a', text: "A) Việc ông N cho anh P thuê tầng một để kinh doanh là thực hiện quyền sử dụng của chủ sở hữu tài sản.", explanation: "Sai, đây là thực hiện quyền định đoạt của chủ sở hữu tài sản.", ans: false },
            { id: 'b', text: "b) Ông N và anh P đều chưa thực hiện tốt nghĩa vụ của chủ thể sản xuất kinh doanh.", explanation: "Đúng, ông N tự ý mở cửa hàng khi chưa có cấp phép, anh P bán hàng không rõ nguồn gốc.", ans: true },
            { id: 'c', text: "c) Ông N chấm dứt hợp đồng và không trả số tiền thuê nhà cho anh P là phù hợp với quyền của chủ sở hữu tài sản.", explanation: "Sai, đây là hành vi không tôn trọng quyền sở hữu tài sản của công dân.", ans: false },
            { id: 'd', text: "d) Việc ông S và anh Q tịch thu tài sản của anh P là phù hợp với quyền của công dân về sở hữu tài sản.", explanation: "Sai. Đây không phải là quyền của chủ sở hữu tài sản mà là chức năng của cơ quan có thẩm quyền.", ans: false }
        ]
    },
    {
        id: 88,
        title: "Câu 88: Hôn nhân gia đình (B, A, C)",
        text: "Vợ chồng anh B, chị A cùng 2 con gái chung sống với mẹ đẻ của anh B là bà C làm giám đốc một công ty tư nhân. Do không ép được chị A sinh thêm con thứ 3 với hi vọng có được cháu trai, bà C đã bịa đặt chị A ngoại tình rồi gửi đơn ra tòa án đề nghị xem xét cho anh B li hôn vợ. Bức xúc với mẹ chồng, chị A đã bí mật rút tiền tiết kiệm của 2 vợ chồng rồi bỏ việc công ty của bà C về kinh doanh cùng mẹ đẻ của chị là bà H. Trong thời gian chị A đi vắng, được bà C hứa sẽ hỗ trợ một khoản tiền lớn, chị M nhân viên của bà C cũng vừa ly hôn, đồng ý mang thai hộ cho anh B. Khi phát hiện mình đã có thai với anh B, chị M đã thông tin tới chị A và yêu cầu chị ly hôn để anh B kết hôn với chị và được chị A đồng ý. Sau khi biết chị gái mình ly hôn, anh Q là em trai chị A đã dùng hung khí uy hiếp và đánh anh B bị thương.",
        items: [
            { id: 'a', text: "a) Bà C có quyền đề nghị tòa án xem xét ly hôn cho anh B và chị A vì chị A đã vi phạm nghiêm trọng đời sống hôn nhân.", explanation: "Sai, ở đây bà C tạo dựng tình huống chị A ngoại tình rồi đề nghị tòa xem xét cho ly hôn là không có căn cứ pháp luật.", ans: false },
            { id: 'b', text: "b) Chị M mang thai hộ cho anh B nên không vi phạm quyền và nghĩa vụ của công dân trong hôn nhân và gia đình.", explanation: "Sai, ở đây anh B đang có vợ và con cũng chưa ly hôn, việc chị M mang thai hộ mà chưa được sự đồng ý của cả chị A là vi phạm.", ans: false },
            { id: 'c', text: "c) Anh Q uy hiếp và đánh anh B bị thương là vi phạm quyền và nghĩa vụ giữa các thành viên trong gia đình.", explanation: "Sai, ở đây xét về quan hệ thì anh B và chị A đã ly hôn nên anh Q sẽ không còn có mối quan hệ gia đình với anh B nên quan hệ này thuộc quan hệ dân sự điều chỉnh.", ans: false },
            { id: 'd', text: "d) Chị A rút tiền tiết kiệm của hai vợ chồng để kinh doanh là phù hợp.", explanation: "Sai, ở đây khi chưa ly hôn tài sản vẫn là tài sản chung của 2 vợ chồng việc chị A rút tiền... là vi phạm quyền tài sản.", ans: false }
        ]
    },
    {
        id: 89,
        title: "Câu 89: Hanh vi BLGD (K, P, Y)",
        text: "Vợ chồng anh K và chị P cùng con nhỏ một năm tuổi sống chung với mẹ chồng là bà Y đồng thời là giám đốc một doanh nghiệp tư nhân. Trong thời gian ở nhà một mình, chị P bị đối tượng trốn lệnh truy nã tên M uy hiếp buộc chị phải cho hắn ẩn nấp trong nhà chị. Do ghen tuông, lại bị bà Y xúi giục, anh K ép chị P phải kí vào đơn ly hôn nhưng bị chị từ chối, bức xúc, anh K nhờ bạn thân là anh X ghép ảnh phản cảm nhằm hạ uy tín của vợ trên mạng xã hội. Vốn có ý coi thường anh K và bà Y, sau khi có được những bằng chứng về việc bà Y ngoài việc sử dụng công nhân không thông qua ký kết hợp đồng lao động và thường xuyên cung cấp các thực phẩm không rõ nguồn gốc bán cho khách hàng, anh H em trai chị P đã làm đơn tố cáo tới cơ quan chức năng, khiến bà Y bị thiệt hại nặng. Khi anh K gặp anh H yêu cầu rút đơn, do thiếu kiềm chế nên anh K và anh H đã lớn tiếng xúc phạm nhau, bức xúc, anh K đã đánh anh H bị thương nhẹ.",
        items: [
            { id: 'a', text: "a) Bà Y và anh K vi phạm quyền và nghĩa vụ của công dân trong hôn nhân và gia đình.", explanation: "Đúng vì bà Y đã xúi giục con trai là anh K ly hôn vợ dù chưa có căn cứ, anh K có hành vi xúc phạm nhân phẩm và danh dự của vợ", ans: true },
            { id: 'b', text: "b) Bà Y đồng thời vi phạm quyền và nghĩa vụ của công dân trong kinh doanh và trong hôn nhân và gia đình.", explanation: "Đúng, bà Y vi phạm nghĩa vụ của chủ thể kinh doanh... vi phạm trong gia đình vì xúi giục con trai ly hôn vợ.", ans: true },
            { id: 'c', text: "c) Anh H vi phạm quyền bình đẳng trong hôn nhân.", explanation: "Sai, anh H chỉ vi phạm quyền và nghĩa vụ của công dân trong gia đình vì anh và anh K có hành vi xúc phạm nhau", ans: false },
            { id: 'd', text: "d) Anh K và anh H vi phạm quyền bình đẳng trong gia đình.", explanation: "Đúng vì hai anh xét về quan hệ gia đình là anh em nhưng lại có hành vi gây gổ, đánh nhau...", ans: true }
        ]
    },
    {
        id: 90,
        title: "Câu 90: Quan hệ hôn nhân (D, M, V)",
        text: "Vợ chồng anh D, chị M cùng con gái sống chung với mẹ chồng là bà V. Phát hiện anh D tự ý thế chấp ngôi nhà của hai vợ chồng theo chỉ đạo của bà V để lấy tiền cho bà kinh doanh, chị M bế con bỏ nhà đi biệt tích. Vào thời điểm đó, vì vợ bị vô sinh, ông K giám đốc nơi chị M làm việc đã thỏa thuận với chị H một bà mẹ đơn thân và được chị đồng ý sinh con cho ông. Sau khi biết mình đã có thai, chị H gây sức ép để ông K bổ nhiệm mình vào vị trí của chị M đang đảm nhiệm. Nhiều lần liên lạc với chị M không được, ông K đã đơn phương chấm dứt hợp đồng với chị rồi bổ nhiệm chị H thay thế. Thấy chị M bị đối xử bất công, anh L em gái chị M đã cung cấp bằng chứng tố cáo bà V trốn đóng bảo hiểm cho người lao động khiến cho việc kinh doanh của bà bị thiệt hại nghiêm trọng.",
        items: [
            { id: 'a', text: "a) Anh D và bà V cùng vi phạm quyền và nghĩa vụ của công dân trong quan hệ tài sản.", explanation: "Sai, chỉ có anh D vi phạm quan hệ tài sản giữa vợ và chồng trong gia đình.", ans: false },
            { id: 'b', text: "b) Ông K và anh D vừa vi phạm quyền và nghĩa vụ của công dân trong hôn nhân vừa vi phạm quyền và nghĩa vụ của vợ và chồng trong gia đình.", explanation: "Sai anh D không vi phạm trong hôn nhân... Ông K đã có vợ mà chung sống với người khác nên mới vi phạm...", ans: false },
            { id: 'c', text: "c) Chị H vi phạm quyền và nghĩa vụ giữa vợ và chồng trong quan hệ hôn nhân.", explanation: "Đúng, chị H là mẹ đơn thân nhưng lại chung sống như vợ chồng với người đang có gia đình là vi phạm hôn nhân.", ans: true },
            { id: 'd', text: "d) Chị M vi phạm quyền và nghĩa vụ giữa vợ và chồng trong quan hệ nhân thân.", explanation: "Đúng hành vi bế con bỏ nhà đi biệt tích của chị M là vi phạm quyền và nghĩa vụ giữa vợ và chồng trong quan hệ nhân thân", ans: true }
        ]
    }
];
